# configuration for https://travis-ci.org/bitcoincash-wallet/bitcoincashj
sudo: sudo
dist: trusty
language: java
jdk: openjdk8
addons:
  postgresql: "9.3"   # min supported version
cache:
  directories:
  - $HOME/.m2

services:
  - mysql

install: true   # disable default because no need to do the mvn install before mvn verify

before_install:
  - wget https://oss.sonatype.org/content/repositories/releases/org/javafxports/dalvik-sdk/8.60.9/dalvik-sdk-8.60.9.zip && unzip dalvik-sdk-8.60.9.zip
  - sudo cp dalvik-sdk/rt/lib/ext/jfxrt.jar $JAVA_HOME/jre/lib/ext
  - sudo cp dalvik-sdk/rt/lib/jfxswt.jar $JAVA_HOME/jre/lib/
  - sudo cp dalvik-sdk/rt/lib/javafx.properties $JAVA_HOME/jre/lib
  - sudo cp dalvik-sdk/rt/lib/javafx.platform.properties $JAVA_HOME/jre/lib
  - sudo cp dalvik-sdk/lib/javafx-mx.jar $JAVA_HOME/lib
  
before_script:
  - psql -c "create user bitcoinj with password 'password';" -U postgres
  - psql -c 'create database bitcoinj_test owner bitcoinj;' -U postgres
  - mysql -e 'CREATE DATABASE bitcoinj_test;'
  - mysql -e "grant all PRIVILEGES on bitcoinj_test.* to 'bitcoinj' identified by 'password';"
  - mysql -e 'SET GLOBAL max_allowed_packet=20971520;'

script:
  - mvn verify -Ptravis -Dmaven.javadoc.skip=true
# to run one specific test - in this case only testFirst100kBlocksWithCustomSchema test in PostgresFullPrunedBlockChainIT class
#  - mvn clean verify -Ptravis -Dmaven.javadoc.skip=true -Dit.test=PostgresFullPrunedBlockChainIT#testFirst100kBlocksWithCustomSchema -Dtest=nothing -DfailIfNoTests=false
# run only mysql integration tests
#  - mvn clean verify -Ptravis -Dmaven.javadoc.skip=true -Dit.test=MySQLFullPrunedBlockChainIT -Dtest=nothing -DfailIfNoTests=false

after_success:
  - cd core
  - mvn jacoco:report coveralls:report
